/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoleRouteImport } from './routes/role'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerRegisterRouteImport } from './routes/worker.register'
import { Route as WorkerHomeRouteImport } from './routes/worker.home'
import { Route as WorkerIdRouteImport } from './routes/worker.$id'
import { Route as CategoryIdRouteImport } from './routes/category.$id'

const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRegisterRoute = WorkerRegisterRouteImport.update({
  id: '/worker/register',
  path: '/worker/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerHomeRoute = WorkerHomeRouteImport.update({
  id: '/worker/home',
  path: '/worker/home',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIdRoute = WorkerIdRouteImport.update({
  id: '/worker/$id',
  path: '/worker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/categories': typeof CategoriesRoute
  '/confirmation': typeof ConfirmationRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/role': typeof RoleRoute
  '/category/$id': typeof CategoryIdRoute
  '/worker/$id': typeof WorkerIdRoute
  '/worker/home': typeof WorkerHomeRoute
  '/worker/register': typeof WorkerRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/categories': typeof CategoriesRoute
  '/confirmation': typeof ConfirmationRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/role': typeof RoleRoute
  '/category/$id': typeof CategoryIdRoute
  '/worker/$id': typeof WorkerIdRoute
  '/worker/home': typeof WorkerHomeRoute
  '/worker/register': typeof WorkerRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/categories': typeof CategoriesRoute
  '/confirmation': typeof ConfirmationRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/role': typeof RoleRoute
  '/category/$id': typeof CategoryIdRoute
  '/worker/$id': typeof WorkerIdRoute
  '/worker/home': typeof WorkerHomeRoute
  '/worker/register': typeof WorkerRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/bookings'
    | '/categories'
    | '/confirmation'
    | '/home'
    | '/login'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/role'
    | '/category/$id'
    | '/worker/$id'
    | '/worker/home'
    | '/worker/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/bookings'
    | '/categories'
    | '/confirmation'
    | '/home'
    | '/login'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/role'
    | '/category/$id'
    | '/worker/$id'
    | '/worker/home'
    | '/worker/register'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/bookings'
    | '/categories'
    | '/confirmation'
    | '/home'
    | '/login'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/role'
    | '/category/$id'
    | '/worker/$id'
    | '/worker/home'
    | '/worker/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  BookingsRoute: typeof BookingsRoute
  CategoriesRoute: typeof CategoriesRoute
  ConfirmationRoute: typeof ConfirmationRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RoleRoute: typeof RoleRoute
  CategoryIdRoute: typeof CategoryIdRoute
  WorkerIdRoute: typeof WorkerIdRoute
  WorkerHomeRoute: typeof WorkerHomeRoute
  WorkerRegisterRoute: typeof WorkerRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/register': {
      id: '/worker/register'
      path: '/worker/register'
      fullPath: '/worker/register'
      preLoaderRoute: typeof WorkerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/home': {
      id: '/worker/home'
      path: '/worker/home'
      fullPath: '/worker/home'
      preLoaderRoute: typeof WorkerHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/$id': {
      id: '/worker/$id'
      path: '/worker/$id'
      fullPath: '/worker/$id'
      preLoaderRoute: typeof WorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  BookingsRoute: BookingsRoute,
  CategoriesRoute: CategoriesRoute,
  ConfirmationRoute: ConfirmationRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RoleRoute: RoleRoute,
  CategoryIdRoute: CategoryIdRoute,
  WorkerIdRoute: WorkerIdRoute,
  WorkerHomeRoute: WorkerHomeRoute,
  WorkerRegisterRoute: WorkerRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
